### ISSUE TITLE
Evaluacion 

### ISSUE THREAD

**Issue by MarianoFunes** [carolinabubenik/MercadoLiebre#1]
Punto 1- Cumple
Punto 2 - Cumple
Punto 3 - Cumple
Punto 4 - Cumple
Punto 5 - Cumple
Punto 6 - Cumple
Punto 7 - Cumple
Punto 8 - Cumple
Punto 9. Tiene buena respuesta, buen armado, esta prolijo. 
Punto 10 Las cards tienen algunos detalles a mejorar como el camion y la superposicion de precios al bajar la resolucion de pantalla.

**Comment by carolinabubenik** [comment]
Punto 10: **Mejorado!**
Por error de interpretación hice que sólo girara el camión al hacer hover sobre él. Mejoré eso y la superposición de precio-descuento.
