### ISSUE TITLE
Evaluación

### ISSUE THREAD

**Issue by abrilalvarez** [carolinabubenik/MercadoLiebre#2]
Punto 1-  Cumple
Punto 2 - Cumple
Punto 3 - Cumple
Punto 4 - Cumple
Punto 5 - Cumple
Punto 6 - Cumple
Punto 7 - Cumple
Punto 8 - Cumple
Punto 9. Está muy bien organizado el contenido. Está acorde a lo planteado en las consignas. Es una muy buena entrega!
Punto 10. Un punto a tener en cuenta es que, al apretar en el artículo del producto, el camión no gira (únicamente cuando aprieto en el ícono) y, además, hay una superposición de elementos (precio y descuento)

**Comment by carolinabubenik** [comment]
Punto 10: **Mejorado!**
Por error de interpretación hice que sólo girara el camión al hacer hover sobre él. Mejoré eso y la superposición de precio-descuento.
